spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myschema
    username: root
    password: pivotal
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true